-- SQL script to insert data into the vulns table

CREATE TABLE IF NOT EXISTS vulns (
    id INT PRIMARY KEY,
    description TEXT,
    author TEXT,
    platform TEXT,
    type TEXT
);

INSERT INTO vulns (id, description, author, platform, type) VALUES (1, '1 Microsoft IIS - WebDAV &#039;ntdll.dll&#039; Remote Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (2, '2 Microsoft IIS 5.0 - WebDAV Remote', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (3, '3 Linux Kernel 2.2.x/2.4.x (RedHat) - &#039;ptrace/kmod&#039; Local Privilege Escalation', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (4, '4 Sun SUNWlldap Library Hostname - Local Buffer Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (5, '5 Microsoft Windows 2000/NT 4 - RPC Locator Service Remote Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (6, '6 WordPress Core 2.0.2 - &#039;cache&#039; Remote Shell Injection', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (7, '7 Samba 2.2.x - Remote Buffer Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (8, '8 SETI@home Clients - Remote Buffer Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (9, '9 Apache 2.x - Memory Leak', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (10, '10 Samba &lt; 2.2.8 (Linux/BSD) - Remote Code Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (37060, '37060 Microsoft Internet Explorer 11 - Crash (PoC) (1)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (11, '11 Apache 2.0.44 (Linux) - Remote Denial of Service', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (12, '12 Linux Kernel &lt; 2.4.20 - Module Loader Privilege Escalation', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (13, '13 Chindi Server 1.0 - Denial of Service', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (15, '15 Apple Mac OSX 10.2.4 - DirectoryService &#039;PATH&#039; Local Privilege Escalation', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (16, '16 PoPToP PPTP 1.1.4-b3 - Remote Command Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (17, '17 Xeneo Web Server 2.2.9.0 - Denial of Service', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (18, '18 Snort 1.9.1 - &#039;p7snort191.sh&#039; Remote Command Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (19, '19 PoPToP PPTP 1.1.4-b3 - &#039;poptop-sane.c&#039; Remote Command Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (20, '20 Microsoft Windows 2000/XP - SMB Authentication Remote Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (21, '21 Qpopper 4.0.x - &#039;poppassd&#039; Privilege Escalation', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (22, '22 Pi3Web 2.0.1 - Denial of Service (PoC)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (23, '23 RealServer &lt; 8.0.2 (Windows Platforms) - Remote Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (24, '24 Sendmail 8.12.8 (BSD) - &#039;Prescan()&#039; Remote Command Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (25, '25 OpenSSH/PAM 3.6.1p1 - Remote Users Discovery Tool', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (26, '26 OpenSSH/PAM 3.6.1p1 - &#039;gossh.sh&#039; Remote Users Ident', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (27, '27 CommuniGate Pro Webmail 4.0.6 - Session Hijacking', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (28, '28 Kerio Personal Firewall 2.1.4 - Remote Code Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (29, '29 Firebird 1.0.2 (FreeBSD 4.7-RELEASE) - Local Privilege Escalation', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (30, '30 Snitz Forums 3.3.03 - Remote Command Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (31, '31 CDRTools CDRecord 2.0 (Mandrake / Slackware) - Local Privilege Escalation', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (32, '32 Microsoft Windows XP - &#039;explorer.exe&#039; Local Buffer Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (33, '33 WsMp3d 0.x - Remote Heap Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (34, '34 Webfroot Shoutbox &lt; 2.32 (Apache) - Local File Inclusion / Remote Code Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (35, '35 Microsoft IIS 5.0 &lt; 5.1 - Remote Denial of Service', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (36, '36 Microsoft Windows - WebDAV Remote Code Execution (2)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (37, '37 Microsoft Internet Explorer - Object Tag (MS03-020)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (38, '38 Apache 2.0.45 - &#039;APR&#039; Crash', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (39, '39 Atftpd 0.6 - &#039;atftpdx.c&#039; Remote Command Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (40, '40 Mandrake Linux 8.2 - &#039;/usr/mail&#039; Local Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (41, '41 mnoGoSearch 3.1.20 - Remote Command Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (42, '42 Winmail Mail Server 2.3 Build 0402 - Remote Format String', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (43, '43 ProFTPd 1.2.9 RC1 - &#039;mod_sql&#039; SQL Injection', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (44, '44 phpBB 2.0.5 - SQL Injection Password Disclosure', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (45, '45 Yahoo Messenger 5.5 - &#039;DSR-ducky.c&#039; Remote Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (46, '46 Kerio MailServer 5.6.3 - Remote Buffer Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (47, '47 phpBB 2.0.4 - PHP Remote File Inclusion', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (48, '48 Microsoft Windows Media Services - Remote (MS03-022)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (49, '49 eXtremail 1.5.x (Linux) - Remote Format Strings', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (50, '50 ColdFusion MX - Remote Development Service', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (51, '51 Microsoft IIS 5.0 - WebDAV Remote Code Execution (3) (xwdav)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (52, '52 ICQ Pro 2003a - &#039;ca1-icq.asm&#039; Password Bypass', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (53, '53 CCBILL CGI - &#039;ccbillx.c&#039; &#039;whereami.cgi&#039; Remote Code Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (54, '54 LeapWare LeapFTP 2.7.x - Remote Buffer Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (55, '55 Samba 2.2.8 - Brute Force Method Remote Command Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (56, '56 Microsoft Windows Media Services - &#039;nsiislog.dll&#039; Remote Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (57, '57 Solaris 2.6/7/8 - &#039;TTYPROMPT in.telnet&#039; Remote Authentication Bypass', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (58, '58 Citadel/UX BBS 6.07 - Remote Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (59, '59 Cisco IOS - IPv4 Packets Denial of Service', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (60, '60 Cisco IOS - &#039;cisco-bug-44020.c&#039; IPv4 Packet Denial of Service', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (61, '61 Microsoft Windows Server 2000 - RPC DCOM Interface Denial of Service', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (62, '62 Cisco IOS - using hping Remote Denial of Service', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (63, '63 miniSQL (mSQL) 1.3 - GID Remote Code Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (64, '64 Microsoft Windows - &#039;RPC DCOM&#039; Remote Buffer Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (65, '65 Microsoft Windows SQL Server - Remote Denial of Service (MS03-031)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (66, '66 Microsoft Windows XP/2000 - &#039;RPC DCOM&#039; Remote (MS03-026)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (67, '67 Apache 1.3.x mod_mylo - Remote Code Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (68, '68 Linux Kernel 2.4.20 - &#039;decode_fh&#039; Denial of Service', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (69, '69 Microsoft Windows - &#039;RPC DCOM&#039; Remote (1)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (70, '70 Microsoft Windows - &#039;RPC DCOM&#039; Remote (2)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (71, '71 XGalaga 2.0.34 (RedHat 9.0) - Local Game', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (72, '72 xtokkaetama 1.0b (RedHat 9.0) - Local Game', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (73, '73 Trillian 0.74 - Remote Denial of Service', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (74, '74 WU-FTPD 2.6.2 - Off-by-One Remote Command Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (75, '75 man-db 2.4.1 - &#039;open_cat_stream()&#039; Local uid=man', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (76, '76 Microsoft Windows - &#039;RPC DCOM&#039; Remote (Universal)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (77, '77 Cisco IOS 12.x/11.x - HTTP Remote Integer Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (78, '78 WU-FTPD 2.6.2 - Remote Command Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (79, '79 DameWare Mini Remote Control Server - System', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (80, '80 Oracle XDB FTP Service - UNLOCK Buffer Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (38772, '38772 ZTE ADSL ZXV10 W300 Modems - Multiple Vulnerabilities', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (81, '81 Microsoft Windows Server 2000 - RSVP Server Authority Hijacking', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (82, '82 Piolet Client 1.05 - Remote Denial of Service', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (83, '83 Microsoft Internet Explorer - Object Data Remote (MS03-032)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (84, '84 Gopherd 3.0.5 - FTP Gateway Remote Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (86, '86 Real Server 7/8/9 (Windows / Linux) - Remote Code Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (88, '88 GtkFtpd 1.0.4 - Remote Buffer Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (89, '89 Linux pam_lib_smb &lt; 1.1.6 - &#039;/bin/login&#039; Remote Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (90, '90 eMule/xMule/LMule - OP_SERVERMESSAGE Format String', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (91, '91 Stunnel 3.24/4.00 - Daemon Hijacking', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (92, '92 Microsoft WordPerfect Document Converter (Windows NT4 Workstation SP5/SP6 French) - File Template Buffer Overflow (MS03-036)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (93, '93 RealPlayer 9 *nix - Local Privilege Escalation', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (94, '94 MyServer 0.4.3 - Denial of Service', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (95, '95 Roger Wilco 1.x - Client Data Buffer Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (96, '96 4D WebSTAR FTP Server Suite - Remote Buffer Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (97, '97 Microsoft Windows - &#039;RPC DCOM&#039; Scanner (MS03-039)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (98, '98 MySQL 3.23.x/4.0.x - Remote Buffer Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (99, '99 Pine 4.56 - Remote Buffer Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (100, '100 Microsoft Windows - &#039;RPC DCOM&#039; Long Filename Overflow (MS03-026)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (101, '101 Solaris Sadmind - Default Configuration Remote Code Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (102, '102 Knox Arkeia Pro 5.1.12 - Backup Remote Code Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (103, '103 Microsoft Windows - &#039;RPC DCOM2&#039; Remote (MS03-039)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (104, '104 hztty 2.0 (RedHat 9.0) - Local Privilege Escalation', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (105, '105 GNU CFEngine 2.-2.0.3 - Remote Stack Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (106, '106 IBM DB2 - Universal Database 7.2 &#039;db2licm&#039; Local Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (107, '107 ProFTPd 1.2.9 rc2 - &#039;.ASCII&#039; File Remote Code Execution (1)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (109, '109 Microsoft Windows - &#039;RPC2&#039; Universal / Denial of Service (RPC3) (MS03-039)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (110, '110 ProFTPd 1.2.7 &lt; 1.2.9rc2 - Remote Code Execution / Brute Force', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (111, '111 Microsoft Windows Messenger Service - Denial of Service (MS03-043)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (112, '112 mIRC 6.1 - &#039;IRC&#039; Protocol Remote Buffer Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (113, '113 Microsoft Exchange Server 2000 - XEXCH50 Heap Overflow (PoC) (MS03-046)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (114, '114 Solaris Runtime Linker (SPARC) - &#039;ld.so.1&#039; Local Buffer Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (115, '115 WU-FTPD 2.6.2 - &#039;wuftpd-freezer.c&#039; Remote Denial of Service', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (116, '116 NIPrint LPD-LPR Print Server 4.10 - Remote Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (117, '117 Microsoft Windows XP/2000 - RPC Remote Non Exec Memory', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (118, '118 OpenBSD - &#039;ibcs2_exec&#039; Kernel Code Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (119, '119 Microsoft Windows XP/2000 - Workstation Service Overflow (MS03-049)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (120, '120 TerminatorX 3.81 - Local Stack Overflow / Local Privilege Escalation', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (121, '121 Microsoft FrontPage Server Extensions - &#039;fp30reg.dll&#039; (MS03-051)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (122, '122 Microsoft Windows - ListBox/ComboBox Control Local (MS03-045)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (123, '123 Microsoft Windows - Workstation Service WKSSVC Remote (MS03-049)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (124, '124 IA WebMail Server 3.x - &#039;iaregdll.dll 1.0.0.5&#039; Remote Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (125, '125 OpenBSD 2.x &lt; 3.3 - &#039;exec_ibcs2_coff_prep_zmagic()&#039; kernel stack overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (126, '126 Apache mod_gzip (with debug_mode) 1.2.26.1a - Remote Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (127, '127 Opera 7.22 - File Creation and Execution (WebServer)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (129, '129 Linux Kernel 2.4.22 - &#039;do_brk()&#039; Local Privilege Escalation (1)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (130, '130 Microsoft Windows XP - Workstation Service Remote (MS03-049)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (131, '131 Linux Kernel 2.4.22 - &#039;do_brk()&#039; Local Privilege Escalation (2)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (132, '132 Apache 1.3.x &lt; 2.0.48 mod_userdir - Remote Users Disclosure', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (133, '133 Eznet 3.5.0 - Remote Stack Overflow / Denial of Service', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (134, '134 HP-UX B11.11 - &#039;/usr/bin/ct&#039; Format String Privilege Escalation', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (135, '135 Microsoft Windows Messenger Service (French) - Remote (MS03-043)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (136, '136 Eznet 3.5.0 - Remote Stack Overflow Universal', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (137, '137 phpBB 2.0.6 - &#039;search_id&#039; SQL Injection / MD5 Hash', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (138, '138 PHP-Nuke 6.9 - &#039;cid&#039; SQL Injection', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (139, '139 Cyrus IMSPD 1.7 - &#039;abook_dbname&#039; Remote Code Execution', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (140, '140 XSOK 1.02 - &#039;-xsokdir&#039; Local Buffer Overflow Game', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (141, '141 Linux Kernel 2.4.23/2.6.0 - &#039;do_mremap()&#039; Bound Checking Validator (1)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (142, '142 Linux Kernel 2.4.23/2.6.0 - &#039;do_mremap()&#039; Bound Checking Validator (2)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (143, '143 lftp 2.6.9 - Remote Stack Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (144, '144 SuSE Linux 9.0 - YaST Configuration Skribt Overwrite Files', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (145, '145 Linux Kernel 2.4.23/2.6.0 - &#039;do_mremap()&#039; Bound Checking Privilege Escalation', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (146, '146 OpenSSL ASN.1 &lt; 0.9.6j/0.9.7b - Brute Forcer for Parsing Bugs', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (147, '147 Need for Speed 2 - Remote Client Buffer Overflow (PoC)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (148, '148 Microsoft Windows XP/2003 - Samba Share Resource Exhaustion (Denial of Service)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (149, '149 RhinoSoft Serv-U FTPd Server 3.x/4.x - &#039;SITE CHMOD&#039; Remote Overflow', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (151, '151 Microsoft Internet Explorer - URL Injection in History List (MS04-004)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (152, '152 rsync 2.5.7 - Local Stack Overflow / Local Privilege Escalation', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (153, '153 Microsoft Windows - ASN.1 &#039;LSASS.exe&#039; Remote Denial of Service (MS04-007)', '', '', '');
INSERT INTO vulns (id, description, author, platform, type) VALUES (154, '154 Linux Kernel 2.2.25/2.4.24/2.6.2 - &#039;mremap()&#039; Validator', '', '', '');
